### ISSUE TITLE
Zobrazení míst na mapě dle časových období

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#1]
Od roku 1948 do roku 1989 se dá daná problematika dělit do 4 fází. Naším úkolem tedy je dát možnost uživateli zobrazit úmrtí na hranicích jen v daných fázích pokud si to bude přát. K tomu je zapotřebí interface, který bude funkčně propojený se zobrazovanými daty.

Dané fáze jsou:
- 1948-1950
- 1951-1965
- 1966-1971
- 1972-1989

Zda by to mělo být pomocí slideru, checklistu nebo záložek, zjistím a rozhodnu do příštího týdne. Je ale třeba asi nejdřív říct, jak to udělat a zda jsme toho vůbec schopni (jsme!).

**Comment by sevcikra** [comment]
![screen shot 2015-06-16 at 10 38 43 pm](https://cloud.githubusercontent.com/assets/1922352/8193941/a4d1b15a-1478-11e5-8b93-5c5450210c2b.png)

Branch merged to master

**Comment by mahish** [comment]
Můžeš, prosím, okomentovat (klidně do kódu) to, kde oddelujes refresh zobrazovani dat od refreshe vykreslovani samotne mapy? Díky.
