### ISSUE TITLE
Data info box

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#10]
Zobrazit další info o daném bodě po najetí myše/po kliknutí na něj.

``` json
"vek_h": "24",
        "statni_prislusnost": "československo - čsr, čssr",
        "gps_bydliste": "49.740692,13.38834",
        "gps_incidentu": "49.898947,12.550136",
        "smer_prechodu": "neurčeno",
        "umrti": "příčinou úmrtí byla střelba pohraničníků, případně příslušní",
        "obdobi_incidentu": "1948 - 1950",
        "rok": 1949
```

V první fázi stačí do native gmaps bubliny. V další fázi zvážíme zda info nezobrazovat ve speciálním boxu jinde na stránce.

_Close this issue with commit_ `close #10`.

**Comment by sevcikra** [comment]
Done and merged to DEV f4c7ad91a640baadb624265787be8ae9e208f5bf
