### ISSUE TITLE
Show markers with identical coordinates

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#14]
V případě několika bodů s identickou pozicí dochází k tomu, že uživatel není schopen zobrazit (tzn- kliknout, najet myší…) informaci o bodu, který neleží na vrchu této skupinky. Klustery tento problém pravděpodobně ještě více komplikují.

_Close this issue with commit named_ `close #14`.

**Comment by mahish** [comment]
Lidi z USTRu nemaj problém s manuálním posunutím postižených bodů tak, aby byli tyto body vedle sebe a nikoli pod sebou.

**Comment by mahish** [comment]
Ideální stav:
![open_kluster](https://cloud.githubusercontent.com/assets/3687943/8549778/e7a2741a-24cc-11e5-9fdf-5c945d48270b.gif)

**Comment by sevcikra** [comment]
I also found this http://jawj.github.io/OverlappingMarkerSpiderfier/demo.html
Looks quite nice!

**Comment by mahish** [comment]
Looks great! There is even possibility of combination with clusters: 

_"I’m told that the OverlappingMarkerSpiderfier also plays nice with clustering — i.e. once you get down to a zoom level where individual markers are shown, these markers then spiderfy happily — but I haven’t yet tried it myself"._

Unfortunately, i was unable to make it work. Probably because i couldnt get values of `myLat` and `myLng` into the Spiderfier script.

Can you test it pls?

**Comment by mahish** [comment]
http://stackoverflow.com/questions/9726920/integrating-spiderfier-js-into-markerclusterer-v3-to-explode-multi-markers-with 

_"MarkerClusterer and OverlappingMS does work together just fine"_
…
_"the key certainly should be in the zoom level of the markercluster"_

**Comment by sevcikra** [comment]
https://github.com/jawj/OverlappingMarkerSpiderfier

**Comment by sevcikra** [comment]
Fixed 8c4689d87d201e7024e377f0d96e329ef53b090d
