### ISSUE TITLE
Highlight active marker

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#16]
To see active marker and so to see to which marker belongs info from infobox.

**Comment by sevcikra** [comment]
http://stackoverflow.com/questions/12727840/google-maps-api-v3-active-marker-onclick

**Comment by sevcikra** [comment]
![screen shot 2015-08-16 at 11 21 39 am](https://cloud.githubusercontent.com/assets/1922352/9292714/5d833862-4409-11e5-9457-50fedff33401.jpg)

**Comment by sevcikra** [comment]
I am currently working with the idea above:

1/ marker gets highlighted (in green when clicked)
2/ all previously clicked markers get shaded (gray)

I used markers from here but they can be easily changed to circles http://mabp.kiev.ua/2010/01/12/google-map-markers/

RS

**Comment by mahish** [comment]
I wouldnt use different visuals for previously clicked markers. Makes things even more complicated. Visually as well as technically. How about previously clicked clusters? Or previously clicked markers within clusters?

Anyway, Ill definitelly take look on this when redesigning actual marker icons.

**Comment by mahish** [comment]
Feel free to pull this so we can test it.

**Comment by mahish** [comment]
Can you pls pull the commit with the active marker only?

I would test previously clicked markers after v0.2 is finished.

**Comment by sevcikra** [comment]
Closed with 47584ff486812d7903ab5175fcb4ba377e3cb284
