### ISSUE TITLE
Dont show any data in info box on page load

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#21]
When page is loaded, by default, the item 136 is selected and its output data are written in info box. 

I suggest no item should be selected on load by default. Or, when selected, its marker must be an active marker.

**Comment by sevcikra** [comment]
I think you have it copied in the HTML. So the fix is to delete that code in https://github.com/mahish/Mapy-usmrceni/blob/dev/index.html#L68.

**Comment by mahish** [comment]
lol, apparently:)
