### ISSUE TITLE
Additional filters

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#24]
Lets make filtrable:
- age — `slider`
- sex — `radio`
- nationality — `dropdown`
- place of residence / of birth (county) — `dropdown`
- place of incident (county or brigade) — `dropdown`
- way of death — `dropdown`

Thus, we need a new box either for the additional filters or for the informations about a selected marker.

At first, Ill prepare basic UI. Then, Radim will make it functional. Eventually, Ill make final UI based on real interaction experience.

**Comment by mahish** [comment]
I finished the filter section. It is not perfect visually but functional. So feel free to start working on this issue. Meanwhile Im going to improve its visual.

![New filter UI](https://i.gyazo.com/cec800ade19cae5d6c663553d6ba2698.gif)

**Comment by mahish** [comment]
The age slider is made with http://refreshless.com/nouislider/ .

**Comment by mahish** [comment]
There should be button to easily resetting all the filters. 

https://github.com/mahish/Mapy-usmrceni/commit/1acf0407bdc77e25a6accf609f9ca81922bc8df9#diff-eacf331f0ffc35d4b482f1d15a887d3bR175

**Comment by mahish** [comment]
Current plan for filter sidebar
- age — slider
- sex — checkbox / dropdown
- ~~nationality~~ citizenship — dropdown
- ~~place of residence / of birth~~ county of residence — dropdown
- ~~place of incident~~ responsible brigade — dropdown
- way of death — dropdown
- direction of crossing the border — checkbox / dropdown

We will have codes for values and a codebook where those values gain their human readable information.

**Comment by mahish** [comment]
New filter:
* direction of crossing — out / in — checkbox

**Comment by sevcikra** [comment]
Can you update this story with what filters are required? The last comment here is an oldie :)

**Comment by mahish** [comment]
Current plan for filter sidebar
- age — slider
- sex — checkbox / dropdown
- citizenship — dropdown
- county of residence — dropdown
- responsible brigade — dropdown
- way of death — dropdown
- direction of crossing the border — checkbox / dropdown
