### ISSUE TITLE
Cluster — Spiderfy workflow

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#29]
Spiderfy works only on maximum map zoom `maxZoom`.
Clusters works only on lower levels of zoom `maxZoom - 1`.
Max map zoom have to be set. Maybe set `maxZoom: 15`?
We need to set zoom event listener to be able to change between spider and cluster without redraw all markers.

**Comment by sevcikra** [comment]
Fixed with a9a5276de7d3e63035e2e57701e3a3fc593caee3
