### ISSUE TITLE
Center map on active marker

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#32]
I would like to try how is it like when I click on a marker map centers on it. It is important function considering the infobox.

**Comment by sevcikra** [comment]
Available to test on this new branch https://github.com/mahish/Mapy-usmrceni/tree/issue-32

**Comment by mahish** [comment]
Works great for me. Im for to merge it.

**Comment by mahish** [comment]
Would be perfect to slow down the animation, though.

**Comment by sevcikra** [comment]
Looks like it would require a lot of additional code http://stackoverflow.com/questions/9335150/slow-down-google-panto-function

**Comment by mahish** [comment]
Well, the example is working, apparently;) If I understand right, you have to link to another js file `easingAnimator.js` and then use in our `map-custom.js` just these lines?

```
dom_elem.addEventListener('click', function(event){
    var point = map.getCenter();

    easingAnimator.easeProp({
        lat: point.lat(),
        lng: point.lng()
    }, points[i]);
});
```
