### ISSUE TITLE
Assign GPS value to administrative area

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#35]
We need to assign GPS values ( `latlng` data ) to administrative areas. It is called [Reverse Geocoding](https://developers.google.com/maps/documentation/geocoding/intro?csw=1#ReverseGeocoding).

Because we have a final set of data, it would be wise to run some script and to add new variable(s) in advance and serve these data packed alrdy in our JSON.

instead of:

``` json
    "gps_bydliste":"49.740692,13.38834",
    "gps_incidentu":"49.898947,12.550136",
```

we add two new variables ( i used [this](http://maps.googleapis.com/maps/api/geocode/json?latlng=49.740692,13.38834&key=) to get the _okres_ data which is `administrative_area_level_2`):

``` json
    "gps_bydliste":"49.740692,13.38834", // actually we dont need this
    "okres_bydliste":"Plzeň-město",
    "gps_incidentu":"49.898947,12.550136", // but we still need this
    "okres_incidentu":"Tachov",
```

So to speak, we need to parse our current JSON thru some script with the geocode api.

**Comment by mahish** [comment]
Unfortunately, this issue is still here. Vojta has GPS values only.

**Comment by mahish** [comment]
An example
https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse

**Comment by sevcikra** [comment]
This is done, no?
