### ISSUE TITLE
Klustery

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#4]
Na jednom místě se může vyskytnout více bodů a ty potom nejde vizuálně odlišit. Proto by bylo dobré nějakým způsobem zvýraznit počet bodů ve stejné lokaci v závislosti na úrovni přibližení. Např. pomocí clusterů: https://googlemaps.github.io/js-marker-clusterer/docs/examples.html

**Comment by sevcikra** [comment]
Basic functionality
![screen shot 2015-06-17 at 11 47 17 pm](https://cloud.githubusercontent.com/assets/1922352/8219568/443aeebe-154b-11e5-89a8-f658238d7b06.png)

**Comment by mahish** [comment]
Super! Asi to pak bude chtít poladit hodnotu toho `gridsize`, možná i na nějaký minimum, aby to klustrovalo jen ty nejbližší (=identický) sousedy.

**Comment by sevcikra** [comment]
Priste muzem zkusit tohle https://www.facebook.com/svethub

RS

2015-06-18 0:51 GMT+02:00 Jiří Maha <notifications@github.com>:
