### ISSUE TITLE
Number of visible markers

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#47]
Show user the information about how many markers are on the map.
1. design @mahish
2. function @sevcikra

**Comment by mahish** [comment]
I pushed branch issue-47. Give it try @sevcikra . I placed a little box to the top right. Quite simple but viable solution. I didnt manage to show number of markers on load so I hardcoded it. Maybe you can take a look on this?

See the code here:
https://github.com/mahish/Mapy-usmrceni/blob/issue-47/js/main.js#L167

**Comment by mahish** [comment]
The best would be to move the `function markersLength` into `function draw` in /js/map-custom.js, right?

**Comment by mahish** [comment]
The `function markersLength` still ignores the age slider on load.

**Comment by sevcikra** [comment]
Done on dev. 
It works for me fine.

RS
