### ISSUE TITLE
Non-linear age slider

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#52]
Most of a values are between 20-30 years of age. To make it easier to navigate we can try to make the slider non-linear http://refreshless.com/nouislider/slider-values/#section-non-linear , something like that:

``` javascript
range: {
    'min': [  5, 1 ], // 5 years old, step by 1 year
    '30%': [ 20, 1 ], // 20 years old, step by 1 year
    '60%': [ 30, 1 ], // 30 years old, step by 1 year
    'max': [ 90, 1 ]  // 90 years old, step by 1 year
}
```

see branch https://github.com/mahish/Mapy-usmrceni/tree/non-linear-slider-(issue-%2352)

**Comment by mahish** [comment]
Error:
![image](https://cloud.githubusercontent.com/assets/3687943/12064910/87f8e962-afce-11e5-89ee-57df0f5ca9b4.png)

It has something with this code, maybe?

``` javascript
format: {
    to: function(value) {
        return value.toString().replace('.00', '');
    },
    from: function(value) {
        return value.toString().replace('.00', '');
    }
}
```

Anyway,  I think it is a bug because the step is defined to be `1` that is integer without a fractional component.

**Comment by sevcikra** [comment]
I don't think so, I commented it out and it starts with strange values:

od 5.00.00 let do 90.00.00 let

Weird.

**Comment by sevcikra** [comment]
It looks like onUpdate event is adding those 00s.

**Comment by sevcikra** [comment]
OK this this line: https://github.com/mahish/Mapy-usmrceni/blob/non-linear-slider-(issue-%2352)/js/main.js#L49

I'll look into it later

**Comment by sevcikra** [comment]
Fixed https://github.com/mahish/Mapy-usmrceni/commit/43ee16e2ef203575b077c8a7f1826d87d6131b0a
